server:
  port: 5555
spring:
  jpa:
    show-sql: true
  datasource:
    db1:
      jdbc-url: jdbc:mysql://localhost:3306/classroom?useUnicode=true&useSSL=false&characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: HPyuko12!!
    db2:
      jdbc-url: jdbc:mysql://localhost:3306/classroom_new?useUnicode=true&useSSL=false&characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: HPyuko12!!
